# -*- coding: utf-8 -*-
"""laboratorio4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dvi8H8gopvdMzR_YRh2s6FMQImnboSX-
"""

c=[-45, 6, 0, 72, 1543]

c
print(c)
len(c)
c[1]
type(c)
c[-1]

a=1

b=2

c

c[a + b]

notas = [91, 99, 89, 53, 79]

sum(notas)

len(notas)

avg = sum(notas)/len(notas)

avg

for i in notas:
  print(i)

for i in reversed(notas):
  print(i)

n = 0
for i in notas:
  n+=i
print (n)

sum(notas)

n = 0
cont = 0
for i in notas:
  n+=i
  cont+=1
print (n/cont)

c[4]=17
print(c)

a_list = []
for number in range (1,6):
  a_list += [number]

a_list

"""Asignacion final"""

a_list = [161, 182, 161, 154, 176, 170, 167, 171, 170, 174]
ac_list = []
ab_list =[]

for i in a_list:
  if ():
    ab_list.append(i)
  else:  
    ac_list.append(i)
print(ab_list)

a_list = [161, 182, 161, 154, 176, 170, 167, 171, 170, 174]

161 in a_list